REPORT_REASONS = [
    ('FAKE_PROFILE', 'Fake Profile'),
    ('IMPERSONATION', 'Impersonating Someone'),
    ('INAPPROPRIATE_PHOTOS', 'Inappropriate Photos'),
    ('INAPPROPRIATE_CONTENT', 'Inappropriate Content'),
    ('HARASSMENT', 'Harassment or Bullying'),
    ('HATE_SPEECH', 'Hate Speech'),
    ('SPAM', 'Spam'),
    ('SCAM_FRAUD', 'Scam or Fraud'),
    ('MISLEADING_INFORMATION', 'Misleading Information'),
    ('UNDERAGE_USER', 'Underage User'),
    ('SEXUAL_CONTENT', 'Sexual Content'),
    ('VIOLENCE_THREATS', 'Violence or Threats'),
    ('SOLICITING_MONEY', 'Asking for Money'),
    ('MARRIED_NOT_DISCLOSED', 'Marital Status Misrepresented'),
    ('CONTACT_INFO_ABUSE', 'Misuse of Contact Information'),
    ('STALKING', 'Stalking'),
    ('BLACKMAIL', 'Blackmail or Extortion'),
    ('OTHER', 'Other'),
]