# Generated by Django 6.0.6 on 2026-07-10 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIDRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('permanent_address', models.CharField(max_length=50)),
                ('document_type', models.CharField(choices=[('Citizenship', 'CITIZENSHIP'), ('Passport', 'PASSPORT'), ('National ID', 'NATIONAL ID'), ('Driving License', 'DRIVING LICENSE'), ('Birth Certificate', 'BIRTH CERTIFICATE'), ('Voter ID', 'VOTER ID'), ('Residence Permit', 'RESIDENCE PERMIT'), ('Other', 'OTHER')], max_length=20)),
                ('front_side', models.URLField()),
                ('back_side', models.URLField(blank=True)),
                ('live_photo', models.URLField()),
                ('status', models.CharField(default='Pending...', max_length=20)),
                ('user_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='identifications.useridrecords')),
            ],
        ),
        migrations.CreateModel(
            name='PackageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Basic', 'BASIC'), ('Premium', 'PREMIUM'), ('VIP', 'VIP')], max_length=15)),
                ('transaction_id', models.IntegerField()),
                ('package_amount', models.IntegerField()),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('paid_via', models.CharField(choices=[('eSewa', 'ESEWA'), ('Khalti', 'KHALTI'), ('ConnectIPS', 'CONNECT_IPS'), ('Visa', 'VISACARD'), ('Mastercard', 'MASTERCARD'), ('American Express', 'AMERICAN_EXPRESS')], max_length=16)),
                ('package_status', models.CharField(choices=[('Pending', 'PENDING'), ('Verified', 'VERIFIED'), ('Cancelled', 'CANCELLED'), ('Rejected', 'REJECTED'), ('Under Review', 'UNDER REVIEW'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', max_length=15)),
                ('user_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_package', to='identifications.useridrecords')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_record', 'transaction_id'), name='unique_identity')],
            },
        ),
    ]
