# Generated by Django 6.0.6 on 2026-07-17 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagehistory',
            name='unique_identity',
        ),
        migrations.DeleteModel(
            name='PackageHistory',
        ),
    ]
