# Generated by Django 6.0.6 on 2026-06-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehistory',
            name='expiry_date',
        ),
    ]
