# Generated by Django 6.0.6 on 2026-08-13 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0002_remove_packagehistory_unique_identity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idverification',
            name='user_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idverification', to='identifications.useridrecords'),
        ),
        migrations.AlterField(
            model_name='useridrecords',
            name='record_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
