# Generated by Django 6.0.6 on 2026-06-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifications', '0002_remove_packagehistory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehistory',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
