export const ProfileOptions = [
  { index: 1, option: "That's Me" },
  { index: 2, option: "Father" },
  { index: 3, option: "Brother" },
  { index: 4, option: "Sister" },
  { index: 5, option: "Mother" },
  { index: 6, option: "Others" },
];

export const GenderOption = [
  { index: 1, option: "Male", value: "MALE" },
  { index: 2, option: "Female", value: "FEMALE" },
  { index: 3, option: "Others", value: "OTHERS" },
];

export const CalendarItems = [
  { label: "AD", value: "AD" },
  { label: "BS", value: "BS" },
];

export const RelativeItems = [
  { label: "Grandfather", value: "Grandfather" },
  { label: "Grandmother", value: "Grandmother" },
  { label: "Uncle", value: "Uncle" },
  { label: "Aunt", value: "Aunt" },
  { label: "Maternal Uncle", value: "Maternal Uncle" },
  { label: "Maternal Aunt", value: "Maternal Aunt" },
  { label: "Brother-in-law", value: "Brother-in-law" },
  { label: "Sister-in-law", value: "Sister-in-law" },
  { label: "Guardian", value: "Guardian" },
  { label: "Family Friend", value: "Family Friend" },
];

export const GotraItems = [
  { label: "Atreya", value: "ATREYA" },
  { label: "Bharadwaj", value: "BHARADWAJ" },
  { label: "Gautam", value: "GAUTAM" },
  { label: "Jamadagni", value: "JAMADAGNI" },
  { label: "Kashyap", value: "KASHYAP" },
  { label: "Kaundinya", value: "KAUNDINYA" },
  { label: "Parashar", value: "PARASHAR" },
  { label: "Shaandilya", value: "SHAANDILYA" },
  { label: "Vashistha", value: "VASHISTHA" },
  { label: "Vatsya", value: "VATSYA" },
  { label: "Agastya", value: "AGASTYA" },
  { label: "Vishwamitra", value: "VISHWAMITRA" },
  { label: "Other", value: "OTHER" },
  { label: "Unknown", value: "UNKNOWN" },
];

export const MaritalStatusItems = [
  { label: "Single", value: "SINGLE" },
  { label: "Never Married", value: "NEVER_MARRIED" },
  { label: "In a Relationship", value: "RELATIONSHIP" },
  { label: "Engaged", value: "ENGAGED" },
  { label: "Married", value: "MARRIED" },
  { label: "Separated", value: "SEPARATED" },
  { label: "Divorced", value: "DIVORCED" },
  { label: "Widowed", value: "WIDOWED" },
  { label: "Marriage Annulled", value: "ANNULLED" },
];

export const ResidencyStatusItems = [
  { label: "Nepal Citizen", value: "NEPAL_CITIZEN" },
  { label: "Permanent Resident (PR)", value: "PERMANENT_RESIDENT" },
  { label: "Temporary Resident", value: "TEMPORARY_RESIDENT" },
  { label: "Work Permit Holder", value: "WORK_PERMIT" },
  { label: "Student Visa Holder", value: "STUDENT_VISA" },
  { label: "Dependent Visa Holder", value: "DEPENDENT_VISA" },
  { label: "Tourist Visa Holder", value: "TOURIST_VISA" },
  { label: "Non-Resident Nepali (NRN)", value: "NON_RESIDENT_NEPALI" },
  { label: "Foreign Citizen", value: "FOREIGN_CITIZEN" },
];

export const ReligionItems = [
  { label: "Hindu", value: "HINDU" },
  { label: "Muslim", value: "MUSLIM" },
  { label: "Christian", value: "CHRISTIAN" },
  { label: "Buddhist", value: "BUDDHIST" },
  { label: "Sikh", value: "SIKH" },
  { label: "Jain", value: "JAIN" },
  { label: "Kirat", value: "KIRAT" },
  { label: "Bon", value: "BON" },
  { label: "Bahá'í", value: "BAHAI" },
  { label: "Jewish", value: "JEWISH" },
  { label: "Zoroastrian", value: "ZOROASTRIAN" },
  { label: "Taoist", value: "TAOIST" },
  { label: "Shinto", value: "SHINTO" },
  { label: "Confucian", value: "CONFUCIAN" },
  { label: "Atheist", value: "ATHEIST" },
  { label: "Agnostic", value: "AGNOSTIC" },
  { label: "Spiritual", value: "SPIRITUAL" },
  { label: "Other", value: "OTHER" },
  { label: "Prefer Not to Say", value: "PREFER_NOT_TO_SAY" },
];

export const CommunityItems = [
  { label: "Brahmin", value: "BRAHMIN" },
  { label: "Chhetri", value: "CHHETRI" },
  { label: "Newar", value: "NEWAR" },
  { label: "Gurung", value: "GURUNG" },
  { label: "Magar", value: "MAGAR" },
  { label: "Tamang", value: "TAMANG" },
  { label: "Rai", value: "RAI" },
  { label: "Limbu", value: "LIMBU" },
  { label: "Sherpa", value: "SHERPA" },
  { label: "Tharu", value: "THARU" },
  { label: "Yadav", value: "YADAV" },
  { label: "Madheshi", value: "MADHESHI" },
  { label: "Dalit", value: "DALIT" },
  { label: "Thakuri", value: "THAKURI" },
  { label: "Muslim", value: "MUSLIM" },
  { label: "Other", value: "OTHER" },
];

export const DietItems = [
  { label: "Vegerarian", value: "Vegerarian" },
  { label: "Non-Vegetarian", value: "Non-Vegetarian" },
];

export const DegreeItems = [
  { label: "Bachelors", value: "Bachelors" },
  { label: "Masters", value: "Masters" },
];

export const WorkingItems = [
  { label: "Private Company", value: "Bachelors" },
  { label: "Governmental Office", value: "Governmental Office" },
];

export const CreativeHobbies = [
  { index: 1, option: "Painting" },
  { index: 2, option: "Drawing" },
  { index: 3, option: "Photography" },
  { index: 4, option: "Graphic Design" },
  { index: 5, option: "Writing" },
  { index: 6, option: "Calligraphy" },
  { index: 7, option: "Crafting" },
  { index: 8, option: "Pottery" },
];

export const MusicAndArtsHobbies = [
  { index: 1, option: "Singing" },
  { index: 2, option: "Playing Guitar" },
  { index: 3, option: "Playing Piano" },
  { index: 4, option: "Dancing" },
  { index: 5, option: "Acting" },
  { index: 6, option: "Music Production" },
  { index: 7, option: "Theater" },
  { index: 8, option: "DJing" },
];

export const SportsAndFitnessHobbies = [
  { index: 1, option: "Gym Workouts" },
  { index: 2, option: "Running" },
  { index: 3, option: "Cycling" },
  { index: 4, option: "Swimming" },
  { index: 5, option: "Football" },
  { index: 6, option: "Cricket" },
  { index: 7, option: "Badminton" },
  { index: 8, option: "Basketball" },
  { index: 9, option: "Yoga" },
  { index: 10, option: "Hiking" },
];

export const TravelAndAdventureHobbies = [
  { index: 1, option: "Traveling" },
  { index: 2, option: "Backpacking" },
  { index: 3, option: "Road Trips" },
  { index: 4, option: "Camping" },
  { index: 5, option: "Trekking" },
  { index: 6, option: "Mountain Climbing" },
  { index: 7, option: "Fishing" },
  { index: 8, option: "Bird Watching" },
];

export const FoodAndLifestyleHobbies = [
  { index: 1, option: "Cooking" },
  { index: 2, option: "Baking" },
  { index: 3, option: "Food Blogging" },
  { index: 4, option: "Coffee Tasting" },
  { index: 5, option: "Tea Tasting" },
  { index: 6, option: "Gardening" },
  { index: 7, option: "Home Decoration" },
  { index: 8, option: "Fashion Styling" },
];

export const LearningAndIntellectualHobbies = [
  { index: 1, option: "Reading Books" },
  { index: 2, option: "Learning Languages" },
  { index: 3, option: "Public Speaking" },
  { index: 4, option: "Chess" },
  { index: 5, option: "Puzzle Solving" },
  { index: 6, option: "History" },
  { index: 7, option: "Science" },
  { index: 8, option: "Researching" },
];

export const TechnologyHobbies = [
  { index: 1, option: "Programming" },
  { index: 2, option: "UI/UX Design" },
  { index: 3, option: "Artificial Intelligence" },
  { index: 4, option: "Game Development" },
  { index: 5, option: "Video Editing" },
  { index: 6, option: "Cybersecurity" },
  { index: 7, option: "Web Development" },
  { index: 8, option: "Content Creation" },
];

export const FunAndEntertainmentHobbies = [
  { index: 1, option: "Gaming" },
  { index: 2, option: "Watching Movies" },
  { index: 3, option: "Watching Series" },
  { index: 4, option: "Anime" },
  { index: 5, option: "Board Games" },
  { index: 6, option: "Card Games" },
  { index: 7, option: "Karaoke" },
  { index: 8, option: "Stand-up Comedy" },
];

export const SocialAndCommunityHobbies = [
  { index: 1, option: "Volunteering" },
  { index: 2, option: "Mentoring" },
  { index: 3, option: "Community Service" },
  { index: 4, option: "Teaching" },
  { index: 5, option: "Event Organizing" },
  { index: 6, option: "Fundraising" },
  { index: 7, option: "Networking" },
  { index: 8, option: "Youth Programs" },
];

export const WellnessAndSpiritualityHobbies = [
  { index: 1, option: "Meditation" },
  { index: 2, option: "Mindfulness" },
  { index: 3, option: "Journaling" },
  { index: 4, option: "Self-Improvement" },
  { index: 5, option: "Nature Walks" },
  { index: 6, option: "Prayer" },
  { index: 7, option: "Breathing Exercises" },
  { index: 8, option: "Spiritual Reading" },
];

export const HeightItems = [
  { label: "3 ft 0 inch", value: "3_0" },
  { label: "3 ft 1 inch", value: "3_1" },
  { label: "3 ft 2 inch", value: "3_2" },
  { label: "3 ft 3 inch", value: "3_3" },
  { label: "3 ft 4 inch", value: "3_4" },
  { label: "3 ft 5 inch", value: "3_5" },
  { label: "3 ft 6 inch", value: "3_6" },
  { label: "3 ft 7 inch", value: "3_7" },
  { label: "3 ft 8 inch", value: "3_8" },
  { label: "3 ft 9 inch", value: "3_9" },
  { label: "3 ft 10 inch", value: "3_10" },
  { label: "3 ft 11 inch", value: "3_11" },
  { label: "4 ft 0 inch", value: "4_0" },
  { label: "4 ft 1 inch", value: "4_1" },
  { label: "4 ft 2 inch", value: "4_2" },
  { label: "4 ft 3 inch", value: "4_3" },
  { label: "4 ft 4 inch", value: "4_4" },
  { label: "4 ft 5 inch", value: "4_5" },
  { label: "4 ft 6 inch", value: "4_6" },
  { label: "4 ft 7 inch", value: "4_7" },
  { label: "4 ft 8 inch", value: "4_8" },
  { label: "4 ft 9 inch", value: "4_9" },
  { label: "4 ft 10 inch", value: "4_10" },
  { label: "4 ft 11 inch", value: "4_11" },
  { label: "5 ft 0 inch", value: "5_0" },
  { label: "5 ft 1 inch", value: "5_1" },
  { label: "5 ft 2 inch", value: "5_2" },
  { label: "5 ft 3 inch", value: "5_3" },
  { label: "5 ft 4 inch", value: "5_4" },
  { label: "5 ft 5 inch", value: "5_5" },
  { label: "5 ft 6 inch", value: "5_6" },
  { label: "5 ft 7 inch", value: "5_7" },
  { label: "5 ft 8 inch", value: "5_8" },
  { label: "5 ft 9 inch", value: "5_9" },
  { label: "5 ft 10 inch", value: "5_10" },
  { label: "5 ft 11 inch", value: "5_11" },
  { label: "6 ft 0 inch", value: "6_0" },
  { label: "6 ft 1 inch", value: "6_1" },
  { label: "6 ft 2 inch", value: "6_2" },
  { label: "6 ft 3 inch", value: "6_3" },
  { label: "6 ft 4 inch", value: "6_4" },
  { label: "6 ft 5 inch", value: "6_5" },
  { label: "6 ft 6 inch", value: "6_6" },
  { label: "6 ft 7 inch", value: "6_7" },
  { label: "6 ft 8 inch", value: "6_8" },
  { label: "6 ft 9 inch", value: "6_9" },
  { label: "6 ft 10 inch", value: "6_10" },
  { label: "6 ft 11 inch", value: "6_11" },
  { label: "7 ft 0 inch", value: "7_0" },
  { label: "7 ft 1 inch", value: "7_1" },
  { label: "7 ft 2 inch", value: "7_2" },
  { label: "7 ft 3 inch", value: "7_3" },
  { label: "7 ft 4 inch", value: "7_4" },
  { label: "7 ft 5 inch", value: "7_5" },
  { label: "7 ft 6 inch", value: "7_6" },
  { label: "7 ft 7 inch", value: "7_7" },
  { label: "7 ft 8 inch", value: "7_8" },
  { label: "7 ft 9 inch", value: "7_9" },
  { label: "7 ft 10 inch", value: "7_10" },
  { label: "7 ft 11 inch", value: "7_11" },
  { label: "8 ft 0 inch", value: "8_0" },
  { label: "8 ft 1 inch", value: "8_1" },
  { label: "8 ft 2 inch", value: "8_2" },
  { label: "8 ft 3 inch", value: "8_3" },
  { label: "8 ft 4 inch", value: "8_4" },
  { label: "8 ft 5 inch", value: "8_5" },
  { label: "8 ft 6 inch", value: "8_6" },
  { label: "8 ft 7 inch", value: "8_7" },
  { label: "8 ft 8 inch", value: "8_8" },
  { label: "8 ft 9 inch", value: "8_9" },
  { label: "8 ft 10 inch", value: "8_10" },
  { label: "8 ft 11 inch", value: "8_11" },
];

export const WeightItems = [
  { label: "30 kg", value: "30" },
  { label: "31 kg", value: "31" },
  { label: "32 kg", value: "32" },
  { label: "33 kg", value: "33" },
  { label: "34 kg", value: "34" },
  { label: "35 kg", value: "35" },
  { label: "36 kg", value: "36" },
  { label: "37 kg", value: "37" },
  { label: "38 kg", value: "38" },
  { label: "39 kg", value: "39" },
  { label: "40 kg", value: "40" },
  { label: "41 kg", value: "41" },
  { label: "42 kg", value: "42" },
  { label: "43 kg", value: "43" },
  { label: "44 kg", value: "44" },
  { label: "45 kg", value: "45" },
  { label: "46 kg", value: "46" },
  { label: "47 kg", value: "47" },
  { label: "48 kg", value: "48" },
  { label: "49 kg", value: "49" },
  { label: "50 kg", value: "50" },
  { label: "51 kg", value: "51" },
  { label: "52 kg", value: "52" },
  { label: "53 kg", value: "53" },
  { label: "54 kg", value: "54" },
  { label: "55 kg", value: "55" },
  { label: "56 kg", value: "56" },
  { label: "57 kg", value: "57" },
  { label: "58 kg", value: "58" },
  { label: "59 kg", value: "59" },
  { label: "60 kg", value: "60" },
  { label: "61 kg", value: "61" },
  { label: "62 kg", value: "62" },
  { label: "63 kg", value: "63" },
  { label: "64 kg", value: "64" },
  { label: "65 kg", value: "65" },
  { label: "66 kg", value: "66" },
  { label: "67 kg", value: "67" },
  { label: "68 kg", value: "68" },
  { label: "69 kg", value: "69" },
  { label: "70 kg", value: "70" },
  { label: "71 kg", value: "71" },
  { label: "72 kg", value: "72" },
  { label: "73 kg", value: "73" },
  { label: "74 kg", value: "74" },
  { label: "75 kg", value: "75" },
  { label: "76 kg", value: "76" },
  { label: "77 kg", value: "77" },
  { label: "78 kg", value: "78" },
  { label: "79 kg", value: "79" },
  { label: "80 kg", value: "80" },
  { label: "81 kg", value: "81" },
  { label: "82 kg", value: "82" },
  { label: "83 kg", value: "83" },
  { label: "84 kg", value: "84" },
  { label: "85 kg", value: "85" },
  { label: "86 kg", value: "86" },
  { label: "87 kg", value: "87" },
  { label: "88 kg", value: "88" },
  { label: "89 kg", value: "89" },
  { label: "90 kg", value: "90" },
  { label: "91 kg", value: "91" },
  { label: "92 kg", value: "92" },
  { label: "93 kg", value: "93" },
  { label: "94 kg", value: "94" },
  { label: "95 kg", value: "95" },
  { label: "96 kg", value: "96" },
  { label: "97 kg", value: "97" },
  { label: "98 kg", value: "98" },
  { label: "99 kg", value: "99" },
  { label: "100 kg", value: "100" },
  { label: "101 kg", value: "101" },
  { label: "102 kg", value: "102" },
  { label: "103 kg", value: "103" },
  { label: "104 kg", value: "104" },
  { label: "105 kg", value: "105" },
  { label: "106 kg", value: "106" },
  { label: "107 kg", value: "107" },
  { label: "108 kg", value: "108" },
  { label: "109 kg", value: "109" },
  { label: "110 kg", value: "110" },
  { label: "111 kg", value: "111" },
  { label: "112 kg", value: "112" },
  { label: "113 kg", value: "113" },
  { label: "114 kg", value: "114" },
  { label: "115 kg", value: "115" },
  { label: "116 kg", value: "116" },
  { label: "117 kg", value: "117" },
  { label: "118 kg", value: "118" },
  { label: "119 kg", value: "119" },
  { label: "120 kg", value: "120" },
];