# Generated by Django 6.0.6 on 2026-07-12 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_conversation_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('Voice', 'VOICE CALL'), ('Video', 'VIDEO CALL')], max_length=5)),
                ('started_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Received', 'RECEIVED BY THE USER'), ('Declined', 'DECLINED BY THE USER'), ('Not Reachable', 'CURRENTLY NOT REACHABLE')], max_length=15)),
                ('caller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='called_user', to='userprofile.userprofile')),
                ('user_conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_call_log', to='conversations.conversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_conversation_id', 'caller_id'), name='unique_calllog')],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('Text', 'TEXT'), ('Voice', 'VOICE'), ('Attachments', 'ATTACHMENTS')], max_length=15)),
                ('text', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('seen', models.BooleanField(blank=True, default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('message_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_user', to='conversations.conversation')),
                ('user_conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_messages', to='conversations.conversation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_conversation_id', 'message_user'), name='unique_messages')],
            },
        ),
    ]
