# Generated by Django 6.0.6 on 2026-07-11 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('profileid', models.CharField(max_length=20, unique=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsersAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=10)),
                ('religion', models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist')], max_length=30)),
                ('diet', models.CharField(default='Non-Vegeratian', max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersAstroDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangalik', models.CharField(choices=[('YES', 'Manglik'), ('NO', 'Non-Manglik'), ('PARTIAL', 'Partially Manglik'), ('UNKNOWN', 'Not Known')], max_length=10)),
                ('sunshine', models.CharField(choices=[('ARIES', 'Aries'), ('TAURUS', 'Taurus'), ('GEMINI', 'Gemini'), ('CANCER', 'Cancer'), ('LEO', 'Leo'), ('VIRGO', 'Virgo'), ('LIBRA', 'Libra'), ('SCORPIO', 'Scorpio'), ('SAGITTARIUS', 'Sagittarius'), ('CAPRICORN', 'Capricorn'), ('AQUARIUS', 'Aquarius'), ('PISCES', 'Pisces')], max_length=15)),
                ('moon_sign', models.CharField(choices=[('MESH', 'Mesh (Aries)'), ('VRISHABHA', 'Vrishabha (Taurus)'), ('MITHUN', 'Mithun (Gemini)'), ('KARKA', 'Karka (Cancer)'), ('SIMHA', 'Simha (Leo)'), ('KANYA', 'Kanya (Virgo)'), ('TULA', 'Tula (Libra)'), ('VRISCHIKA', 'Vrischika (Scorpio)'), ('DHANU', 'Dhanu (Sagittarius)'), ('MAKARA', 'Makara (Capricorn)'), ('KUMBHA', 'Kumbha (Aquarius)'), ('MEENA', 'Meena (Pisces)')], max_length=15)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astro_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.URLField(default='https://www.pinterest.com/pin/573364596331091460/')),
                ('cover_picture', models.URLField(default='https://i.pinimg.com/736x/07/fb/34/07fb3452c4640d881a16d08c2e314f3e.jpg')),
                ('bio', models.TextField(default='LamiSewa user')),
                ('profile_handler', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(choices=[('SEE', 'SEE / SLC'), ('PLUS_TWO', '+2 / Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('M_PHIL', 'M.Phil'), ('PHD', 'PhD / Doctorate'), ('POSTDOC', 'Postdoctoral'), ('PROFESSIONAL', 'Professional Certification'), ('OTHER', 'Other')], max_length=30)),
                ('college_name', models.CharField(max_length=255)),
                ('working_as', models.CharField(choices=[('PRIVATE', 'Private Job'), ('GOVERNMENT', 'Government Job'), ('ENTREPRENEUR', 'Entrepreneur'), ('BUSINESS_OWNER', 'Business Owner'), ('SELF_EMPLOYED', 'Self Employed'), ('FREELANCER', 'Freelancer'), ('STUDENT', 'Student'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('HOMEMAKER', 'Homemaker'), ('AGRICULTURE', 'Agriculture / Farming'), ('MILITARY', 'Military / Armed Forces'), ('NON_PROFIT', 'Non-Profit Organization'), ('RELIGIOUS_SERVICE', 'Religious Service'), ('OTHER', 'Other')], max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('company_or_organization_name', models.CharField(max_length=255)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_type', models.CharField(choices=[('NUCLEAR', 'Nuclear Family'), ('JOINT', 'Joint Family'), ('EXTENDED', 'Extended Family'), ('SINGLE_PARENT', 'Single Parent Family'), ('GUARDIAN_FAMILY', 'Living with Guardian/Relatives'), ('OTHER', 'Other')], max_length=30)),
                ('total_family_members', models.IntegerField()),
                ('siblings', models.IntegerField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersFeaturedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image2', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image3', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image4', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image5', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image6', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_image', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersHobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby1', models.CharField(max_length=20)),
                ('hobby2', models.CharField(max_length=20)),
                ('hobby3', models.CharField(max_length=20)),
                ('hobby4', models.CharField(max_length=20)),
                ('hobby5', models.CharField(max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersPartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_ranging', models.CharField(default='20 to 30', max_length=10)),
                ('maritalstatus', models.CharField(choices=[('SINGLE', 'Single'), ('NEVER_MARRIED', 'Never Married'), ('RELATIONSHIP', 'In a Relationship'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('ANNULLED', 'Marriage Annulled')], max_length=15)),
                ('living_in', models.CharField(max_length=50)),
                ('partner_religion', models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist')], max_length=30)),
                ('partner_diet', models.CharField(default='Non-Vegeratian', max_length=20)),
                ('partner_education', models.CharField(choices=[('SEE', 'SEE / SLC'), ('PLUS_TWO', '+2 / Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('M_PHIL', 'M.Phil'), ('PHD', 'PhD / Doctorate'), ('POSTDOC', 'Postdoctoral'), ('PROFESSIONAL', 'Professional Certification'), ('OTHER', 'Other')], max_length=30)),
                ('partner_profession', models.CharField(max_length=50)),
                ('partner_mangalik', models.CharField(choices=[('YES', 'Manglik'), ('NO', 'Non-Manglik'), ('PARTIAL', 'Partially Manglik'), ('UNKNOWN', 'Not Known')], max_length=10)),
                ('preference_summary', models.TextField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maritalstatus', models.CharField(choices=[('SINGLE', 'Single'), ('NEVER_MARRIED', 'Never Married'), ('RELATIONSHIP', 'In a Relationship'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('ANNULLED', 'Marriage Annulled')], max_length=15)),
                ('gotra', models.CharField(choices=[('ATREYA', 'Atreya'), ('BHARADWAJ', 'Bharadwaj'), ('GAUTAM', 'Gautam'), ('JAMADAGNI', 'Jamadagni'), ('KASHYAP', 'Kashyap'), ('KAUNDINYA', 'Kaundinya'), ('PARASHAR', 'Parashar'), ('SHAANDILYA', 'Shaandilya'), ('VASHISTHA', 'Vashistha'), ('VATSYA', 'Vatsya'), ('AGASTYA', 'Agastya'), ('VISHWAMITRA', 'Vishwamitra'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=15)),
                ('current_living_country', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('residency_status', models.CharField(choices=[('NEPAL_CITIZEN', 'Nepal Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident (PR)'), ('TEMPORARY_RESIDENT', 'Temporary Resident'), ('WORK_PERMIT', 'Work Permit Holder'), ('STUDENT_VISA', 'Student Visa Holder'), ('DEPENDENT_VISA', 'Dependent Visa Holder'), ('TOURIST_VISA', 'Tourist Visa Holder'), ('NON_RESIDENT_NEPALI', 'Non-Resident Nepali (NRN)'), ('FOREIGN_CITIZEN', 'Foreign Citizen')], max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.URLField(blank=True)),
                ('storyviews', models.IntegerField(default=0)),
                ('userprofileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='userprofile.userprofile')),
            ],
        ),
    ]
