# Generated by Django 6.0.6 on 2026-06-15 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=15)),
                ('profileid', models.CharField(max_length=20, unique=True)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maritalstatus', models.CharField(choices=[('SINGLE', 'Single'), ('NEVER_MARRIED', 'Never Married'), ('RELATIONSHIP', 'In a Relationship'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('ANNULLED', 'Marriage Annulled')], max_length=15)),
                ('gotra', models.CharField(choices=[('ATREYA', 'Atreya'), ('BHARADWAJ', 'Bharadwaj'), ('GAUTAM', 'Gautam'), ('JAMADAGNI', 'Jamadagni'), ('KASHYAP', 'Kashyap'), ('KAUNDINYA', 'Kaundinya'), ('PARASHAR', 'Parashar'), ('SHAANDILYA', 'Shaandilya'), ('VASHISTHA', 'Vashistha'), ('VATSYA', 'Vatsya'), ('AGASTYA', 'Agastya'), ('VISHWAMITRA', 'Vishwamitra'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], max_length=15)),
                ('current_living_country', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('residency_status', models.CharField(choices=[('NEPAL_CITIZEN', 'Nepal Citizen'), ('PERMANENT_RESIDENT', 'Permanent Resident (PR)'), ('TEMPORARY_RESIDENT', 'Temporary Resident'), ('WORK_PERMIT', 'Work Permit Holder'), ('STUDENT_VISA', 'Student Visa Holder'), ('DEPENDENT_VISA', 'Dependent Visa Holder'), ('TOURIST_VISA', 'Tourist Visa Holder'), ('NON_RESIDENT_NEPALI', 'Non-Resident Nepali (NRN)'), ('FOREIGN_CITIZEN', 'Foreign Citizen')], max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby1', models.CharField(max_length=20)),
                ('hobby2', models.CharField(max_length=20)),
                ('hobby3', models.CharField(max_length=20)),
                ('hobby4', models.CharField(max_length=20)),
                ('hobby5', models.CharField(max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image2', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image3', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image4', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image5', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('image6', models.URLField(blank=True, default='https://www.pinterest.com/pin/573364596331091460/')),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_image', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=10)),
                ('religion', models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist')], max_length=30)),
                ('diet', models.CharField(default='Non-Vegeratian', max_length=20)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UsersBasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('profile_picture', models.URLField(default='https://www.pinterest.com/pin/573364596331091460/')),
                ('cover_picture', models.URLField(default='https://i.pinimg.com/736x/07/fb/34/07fb3452c4640d881a16d08c2e314f3e.jpg')),
                ('bio', models.TextField(default='Bihebari user')),
                ('profile_handler', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_info', to='userprofile.userprofile')),
            ],
        ),
    ]
