# Generated by Django 6.0.6 on 2026-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbasicinfo',
            name='bio',
            field=models.TextField(default='LamiSewa user'),
        ),
    ]
