# Generated by Django 6.0.6 on 2026-06-15 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstroDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangalik', models.CharField(choices=[('YES', 'Manglik'), ('NO', 'Non-Manglik'), ('PARTIAL', 'Partially Manglik'), ('UNKNOWN', 'Not Known')], max_length=10)),
                ('sunshine', models.CharField(choices=[('ARIES', 'Aries'), ('TAURUS', 'Taurus'), ('GEMINI', 'Gemini'), ('CANCER', 'Cancer'), ('LEO', 'Leo'), ('VIRGO', 'Virgo'), ('LIBRA', 'Libra'), ('SCORPIO', 'Scorpio'), ('SAGITTARIUS', 'Sagittarius'), ('CAPRICORN', 'Capricorn'), ('AQUARIUS', 'Aquarius'), ('PISCES', 'Pisces')], max_length=15)),
                ('moon_sign', models.CharField(choices=[('MESH', 'Mesh (Aries)'), ('VRISHABHA', 'Vrishabha (Taurus)'), ('MITHUN', 'Mithun (Gemini)'), ('KARKA', 'Karka (Cancer)'), ('SIMHA', 'Simha (Leo)'), ('KANYA', 'Kanya (Virgo)'), ('TULA', 'Tula (Libra)'), ('VRISCHIKA', 'Vrischika (Scorpio)'), ('DHANU', 'Dhanu (Sagittarius)'), ('MAKARA', 'Makara (Capricorn)'), ('KUMBHA', 'Kumbha (Aquarius)'), ('MEENA', 'Meena (Pisces)')], max_length=15)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astro_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(choices=[('SEE', 'SEE / SLC'), ('PLUS_TWO', '+2 / Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('M_PHIL', 'M.Phil'), ('PHD', 'PhD / Doctorate'), ('POSTDOC', 'Postdoctoral'), ('PROFESSIONAL', 'Professional Certification'), ('OTHER', 'Other')], max_length=30)),
                ('college_name', models.CharField(max_length=255)),
                ('working_as', models.CharField(choices=[('PRIVATE', 'Private Job'), ('GOVERNMENT', 'Government Job'), ('ENTREPRENEUR', 'Entrepreneur'), ('BUSINESS_OWNER', 'Business Owner'), ('SELF_EMPLOYED', 'Self Employed'), ('FREELANCER', 'Freelancer'), ('STUDENT', 'Student'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('HOMEMAKER', 'Homemaker'), ('AGRICULTURE', 'Agriculture / Farming'), ('MILITARY', 'Military / Armed Forces'), ('NON_PROFIT', 'Non-Profit Organization'), ('RELIGIOUS_SERVICE', 'Religious Service'), ('OTHER', 'Other')], max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('company_or_organization_name', models.CharField(max_length=255)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_type', models.CharField(choices=[('NUCLEAR', 'Nuclear Family'), ('JOINT', 'Joint Family'), ('EXTENDED', 'Extended Family'), ('SINGLE_PARENT', 'Single Parent Family'), ('GUARDIAN_FAMILY', 'Living with Guardian/Relatives'), ('OTHER', 'Other')], max_length=30)),
                ('total_family_members', models.IntegerField()),
                ('siblings', models.IntegerField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_ranging', models.CharField(default='20 to 30', max_length=10)),
                ('maritalstatus', models.CharField(choices=[('SINGLE', 'Single'), ('NEVER_MARRIED', 'Never Married'), ('RELATIONSHIP', 'In a Relationship'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('ANNULLED', 'Marriage Annulled')], max_length=15)),
                ('living_in', models.CharField(max_length=50)),
                ('partner_religion', models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist')], max_length=30)),
                ('partner_diet', models.CharField(default='Non-Vegeratian', max_length=20)),
                ('partner_education', models.CharField(choices=[('SEE', 'SEE / SLC'), ('PLUS_TWO', '+2 / Higher Secondary'), ('DIPLOMA', 'Diploma'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('M_PHIL', 'M.Phil'), ('PHD', 'PhD / Doctorate'), ('POSTDOC', 'Postdoctoral'), ('PROFESSIONAL', 'Professional Certification'), ('OTHER', 'Other')], max_length=30)),
                ('partner_profession', models.CharField(max_length=50)),
                ('partner_mangalik', models.CharField(choices=[('YES', 'Manglik'), ('NO', 'Non-Manglik'), ('PARTIAL', 'Partially Manglik'), ('UNKNOWN', 'Not Known')], max_length=10)),
                ('preference_summary', models.TextField()),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_preference', to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story1', models.URLField()),
                ('story1views', models.IntegerField(default=0)),
                ('story2', models.URLField()),
                ('story2views', models.IntegerField(default=0)),
                ('story3', models.URLField()),
                ('story3views', models.IntegerField(default=0)),
                ('story4', models.URLField()),
                ('story4views', models.IntegerField(default=0)),
                ('story5', models.URLField()),
                ('story5views', models.IntegerField(default=0)),
                ('userprofileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='userprofile.userprofile')),
            ],
        ),
    ]
