# Generated by Django 6.0.6 on 2026-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersadditionalinfo',
            name='height',
            field=models.CharField(choices=[('3_0', '3 ft 0 inch'), ('3_1', '3 ft 1 inch'), ('3_2', '3 ft 2 inch'), ('3_3', '3 ft 3 inch'), ('3_4', '3 ft 4 inch'), ('3_5', '3 ft 5 inch'), ('3_6', '3 ft 6 inch'), ('3_7', '3 ft 7 inch'), ('3_8', '3 ft 8 inch'), ('3_9', '3 ft 9 inch'), ('3_10', '3 ft 10 inch'), ('3_11', '3 ft 11 inch'), ('4_0', '4 ft 0 inch'), ('4_1', '4 ft 1 inch'), ('4_2', '4 ft 2 inch'), ('4_3', '4 ft 3 inch'), ('4_4', '4 ft 4 inch'), ('4_5', '4 ft 5 inch'), ('4_6', '4 ft 6 inch'), ('4_7', '4 ft 7 inch'), ('4_8', '4 ft 8 inch'), ('4_9', '4 ft 9 inch'), ('4_10', '4 ft 10 inch'), ('4_11', '4 ft 11 inch'), ('5_0', '5 ft 0 inch'), ('5_1', '5 ft 1 inch'), ('5_2', '5 ft 2 inch'), ('5_3', '5 ft 3 inch'), ('5_4', '5 ft 4 inch'), ('5_5', '5 ft 5 inch'), ('5_6', '5 ft 6 inch'), ('5_7', '5 ft 7 inch'), ('5_8', '5 ft 8 inch'), ('5_9', '5 ft 9 inch'), ('5_10', '5 ft 10 inch'), ('5_11', '5 ft 11 inch'), ('6_0', '6 ft 0 inch'), ('6_1', '6 ft 1 inch'), ('6_2', '6 ft 2 inch'), ('6_3', '6 ft 3 inch'), ('6_4', '6 ft 4 inch'), ('6_5', '6 ft 5 inch'), ('6_6', '6 ft 6 inch'), ('6_7', '6 ft 7 inch'), ('6_8', '6 ft 8 inch'), ('6_9', '6 ft 9 inch'), ('6_10', '6 ft 10 inch'), ('6_11', '6 ft 11 inch'), ('7_0', '7 ft 0 inch'), ('7_1', '7 ft 1 inch'), ('7_2', '7 ft 2 inch'), ('7_3', '7 ft 3 inch'), ('7_4', '7 ft 4 inch'), ('7_5', '7 ft 5 inch'), ('7_6', '7 ft 6 inch'), ('7_7', '7 ft 7 inch'), ('7_8', '7 ft 8 inch'), ('7_9', '7 ft 9 inch'), ('7_10', '7 ft 10 inch'), ('7_11', '7 ft 11 inch'), ('8_0', '8 ft 0 inch'), ('8_1', '8 ft 1 inch'), ('8_2', '8 ft 2 inch'), ('8_3', '8 ft 3 inch'), ('8_4', '8 ft 4 inch'), ('8_5', '8 ft 5 inch'), ('8_6', '8 ft 6 inch'), ('8_7', '8 ft 7 inch'), ('8_8', '8 ft 8 inch'), ('8_9', '8 ft 9 inch'), ('8_10', '8 ft 10 inch'), ('8_11', '8 ft 11 inch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersadditionalinfo',
            name='religion',
            field=models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('SIKH', 'Sikh'), ('JAIN', 'Jain'), ('KIRAT', 'Kirat'), ('BON', 'Bon'), ('BAHAI', "Bahá'í"), ('JEWISH', 'Jewish'), ('ZOROASTRIAN', 'Zoroastrian'), ('TAOIST', 'Taoist'), ('SHINTO', 'Shinto'), ('CONFUCIAN', 'Confucian'), ('ATHEIST', 'Atheist'), ('AGNOSTIC', 'Agnostic'), ('SPIRITUAL', 'Spiritual'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usersadditionalinfo',
            name='weight',
            field=models.CharField(choices=[('30', '30 kg'), ('31', '31 kg'), ('32', '32 kg'), ('33', '33 kg'), ('34', '34 kg'), ('35', '35 kg'), ('36', '36 kg'), ('37', '37 kg'), ('38', '38 kg'), ('39', '39 kg'), ('40', '40 kg'), ('41', '41 kg'), ('42', '42 kg'), ('43', '43 kg'), ('44', '44 kg'), ('45', '45 kg'), ('46', '46 kg'), ('47', '47 kg'), ('48', '48 kg'), ('49', '49 kg'), ('50', '50 kg'), ('51', '51 kg'), ('52', '52 kg'), ('53', '53 kg'), ('54', '54 kg'), ('55', '55 kg'), ('56', '56 kg'), ('57', '57 kg'), ('58', '58 kg'), ('59', '59 kg'), ('60', '60 kg'), ('61', '61 kg'), ('62', '62 kg'), ('63', '63 kg'), ('64', '64 kg'), ('65', '65 kg'), ('66', '66 kg'), ('67', '67 kg'), ('68', '68 kg'), ('69', '69 kg'), ('70', '70 kg'), ('71', '71 kg'), ('72', '72 kg'), ('73', '73 kg'), ('74', '74 kg'), ('75', '75 kg'), ('76', '76 kg'), ('77', '77 kg'), ('78', '78 kg'), ('79', '79 kg'), ('80', '80 kg'), ('81', '81 kg'), ('82', '82 kg'), ('83', '83 kg'), ('84', '84 kg'), ('85', '85 kg'), ('86', '86 kg'), ('87', '87 kg'), ('88', '88 kg'), ('89', '89 kg'), ('90', '90 kg'), ('91', '91 kg'), ('92', '92 kg'), ('93', '93 kg'), ('94', '94 kg'), ('95', '95 kg'), ('96', '96 kg'), ('97', '97 kg'), ('98', '98 kg'), ('99', '99 kg'), ('100', '100 kg'), ('101', '101 kg'), ('102', '102 kg'), ('103', '103 kg'), ('104', '104 kg'), ('105', '105 kg'), ('106', '106 kg'), ('107', '107 kg'), ('108', '108 kg'), ('109', '109 kg'), ('110', '110 kg'), ('111', '111 kg'), ('112', '112 kg'), ('113', '113 kg'), ('114', '114 kg'), ('115', '115 kg'), ('116', '116 kg'), ('117', '117 kg'), ('118', '118 kg'), ('119', '119 kg'), ('120', '120 kg')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userspartnerpreference',
            name='partner_religion',
            field=models.CharField(choices=[('HINDU', 'Hindu'), ('MUSLIM', 'Muslim'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('SIKH', 'Sikh'), ('JAIN', 'Jain'), ('KIRAT', 'Kirat'), ('BON', 'Bon'), ('BAHAI', "Bahá'í"), ('JEWISH', 'Jewish'), ('ZOROASTRIAN', 'Zoroastrian'), ('TAOIST', 'Taoist'), ('SHINTO', 'Shinto'), ('CONFUCIAN', 'Confucian'), ('ATHEIST', 'Atheist'), ('AGNOSTIC', 'Agnostic'), ('SPIRITUAL', 'Spiritual'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
