# Generated by Django 6.0.6 on 2026-08-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_usersadditionalinfo_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershobbies',
            name='hobby1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usershobbies',
            name='hobby2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usershobbies',
            name='hobby3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usershobbies',
            name='hobby4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usershobbies',
            name='hobby5',
            field=models.CharField(max_length=255),
        ),
    ]
