# Generated by Django 6.0.6 on 2026-07-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_usersbasicinfo_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalInfo',
            new_name='UsersAdditionalInfo',
        ),
        migrations.RenameModel(
            old_name='AstroDetail',
            new_name='UsersAstroDetail',
        ),
        migrations.RenameModel(
            old_name='Career',
            new_name='UsersCareer',
        ),
        migrations.RenameModel(
            old_name='FamilyDetail',
            new_name='UsersFamilyDetail',
        ),
        migrations.RenameModel(
            old_name='FeaturedImages',
            new_name='UsersFeaturedImages',
        ),
        migrations.RenameModel(
            old_name='Hobbies',
            new_name='UsersHobbies',
        ),
        migrations.RenameModel(
            old_name='PartnerPreference',
            new_name='UsersPartnerPreference',
        ),
        migrations.RenameModel(
            old_name='PersonalInfo',
            new_name='UsersPersonalInfo',
        ),
        migrations.RenameModel(
            old_name='Stories',
            new_name='UsersStories',
        ),
    ]
