# Generated by Django 6.0.6 on 2026-06-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_astrodetail_career_familydetail_partnerpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='story1',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story2',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story3',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story4',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='story5',
            field=models.URLField(blank=True),
        ),
    ]
