# Generated by Django 6.0.6 on 2026-07-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_additionalinfo_usersadditionalinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersstories',
            name='userprofileid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='userprofile.userprofile'),
        ),
    ]
