# Generated by Django 6.0.6 on 2026-06-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_stories_story1_alter_stories_story2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='story1',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='stories',
            old_name='story1views',
            new_name='storyviews',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story2',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story2views',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story3',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story3views',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story4',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story4views',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story5',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='story5views',
        ),
    ]
