# Generated by Django 6.0.6 on 2026-07-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Basic', 'BASIC'), ('Premium', 'PREMIUM'), ('VIP', 'VIP')], max_length=15)),
                ('transaction_id', models.IntegerField()),
                ('package_amount', models.IntegerField()),
                ('purchased_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('paid_via', models.CharField(choices=[('eSewa', 'ESEWA'), ('Khalti', 'KHALTI'), ('ConnectIPS', 'CONNECT_IPS'), ('Visa', 'VISACARD'), ('Mastercard', 'MASTERCARD'), ('American Express', 'AMERICAN_EXPRESS')], max_length=16)),
                ('payment_status', models.CharField(default='Paid', max_length=10)),
                ('package_status', models.CharField(choices=[('Pending', 'PENDING'), ('Verified', 'VERIFIED'), ('Cancelled', 'CANCELLED'), ('Rejected', 'REJECTED'), ('Under Review', 'UNDER REVIEW'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', max_length=15)),
                ('user_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_payments', to='payments.userpaymentrecords')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_record', 'transaction_id'), name='unique_identity')],
            },
        ),
    ]
