# Generated by Django 6.0.6 on 2026-08-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_userpaymentrecords_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymentrecords',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paymentdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
