# Generated by Django 6.0.6 on 2026-06-15 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0003_alter_stories_story1_alter_stories_story2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacyid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favourites_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by_users', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_users', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'favourites_user'), name='unique_favourite')],
            },
        ),
        migrations.CreateModel(
            name='BlockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('blocked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'blocked_id'), name='unique_block')],
            },
        ),
    ]
