# Generated by Django 6.0.6 on 2026-07-10 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacyid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE_PROFILE', 'Fake Profile'), ('IMPERSONATION', 'Impersonating Someone'), ('INAPPROPRIATE_PHOTOS', 'Inappropriate Photos'), ('INAPPROPRIATE_CONTENT', 'Inappropriate Content'), ('HARASSMENT', 'Harassment or Bullying'), ('HATE_SPEECH', 'Hate Speech'), ('SPAM', 'Spam'), ('SCAM_FRAUD', 'Scam or Fraud'), ('MISLEADING_INFORMATION', 'Misleading Information'), ('UNDERAGE_USER', 'Underage User'), ('SEXUAL_CONTENT', 'Sexual Content'), ('VIOLENCE_THREATS', 'Violence or Threats'), ('SOLICITING_MONEY', 'Asking for Money'), ('MARRIED_NOT_DISCLOSED', 'Marital Status Misrepresented'), ('CONTACT_INFO_ABUSE', 'Misuse of Contact Information'), ('STALKING', 'Stalking'), ('BLACKMAIL', 'Blackmail or Extortion'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='The reported user used abusive language or inappropriate behavior.')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Verified', 'VERIFIED'), ('Cancelled', 'CANCELLED'), ('Rejected', 'REJECTED'), ('Under Review', 'UNDER REVIEW'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reported_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reporting_other', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'reported_id'), name='unique_report_data')],
            },
        ),
        migrations.CreateModel(
            name='FollowDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_following_other', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'following_user'), name='unique_follow')],
            },
        ),
        migrations.CreateModel(
            name='FavouriteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favourites_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by_users', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_users', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'favourites_user'), name='unique_favourite')],
            },
        ),
        migrations.CreateModel(
            name='BlockDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('blocked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to='userprofile.userprofile')),
                ('user_privacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='privacy.userprivacy')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_privacy', 'blocked_id'), name='unique_block')],
            },
        ),
    ]
