# Generated by Django 6.0.6 on 2026-06-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_followdetail_reportuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Verified', 'VERIFIED'), ('Cancelled', 'CANCELLED'), ('Rejected', 'REJECTED'), ('Under Review', 'UNDER REVIEW'), ('Completed', 'COMPLETED'), ('Failed', 'FAILED')], default='Pending', max_length=30),
        ),
    ]
